# -*- coding: utf-8 -*-
"""chatbot .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiwNUp6rk0hY5mOQlh_dlnGIhh14cwPo
"""

import json
import random

import numpy as np

from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

stemmer = PorterStemmer()

intents = {
    "intents":[
        {
            "tag":"greeting",
            "patterns":["hello","hi","hey","good morning"],
            "responses":[
                "Hello Ravi!",
                "Hi, How can I help you?",
                "Welcome!"
            ]
        },
        {
            "tag":"python",
            "patterns":[
                "what is python",
                "python language",
                "tell me about python"
            ],
            "responses":[
                "Python is a high-level programming language."
            ]
        },
        {
            "tag":"bye",
            "patterns":["bye","goodbye","see you"],
            "responses":[
                "Goodbye!",
                "Take Care!"
            ]
        }
    ]
}

X = []
y = []

for intent in intents["intents"]:

    tag = intent["tag"]

    for pattern in intent["patterns"]:

        X.append(pattern)
        y.append(tag)

print(X)
print(y)

vectorizer = CountVectorizer()

X_vectors = vectorizer.fit_transform(X)

model = MultinomialNB()

model.fit(X_vectors, y)

print("Model Trained Successfully")

def chatbot_response(user_input):

    user_vector = vectorizer.transform([user_input])

    prediction = model.predict(user_vector)[0]

    for intent in intents["intents"]:

        if intent["tag"] == prediction:

            return random.choice(intent["responses"])

while True:

    user = input("You : ")

    if user.lower() == "exit":
        print("Bot : Goodbye")
        break

    response = chatbot_response(user)

    print("Bot :", response)

import pickle

pickle.dump(model, open("chatbot_model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))